# Dependencies
markdown:         kramdown
highlighter:      rouge
encoding: utf-8

# Permalinks
permalink:        pretty


# Setup
title:            aBailey
tagline:          'Alistairs GitHub Project Pages'
description:      'Find me online at <a href="http://cmg.soton.ac.uk/people/ab604/">cmg.soton.ac.uk</a> and <a href="https://github.com/ab604">Github</a>.'
url:              http://ab604.github.io/
baseurl:          /

author:
  name:           'Alistair Bailey'
  email:           ab604@soton.ac.uk

paginate:         5


github:
  repo:           https://github.com/ab604/ab604.github.io.git
  

